export { default as Hero } from './Hero';
export { default as HowItWorks } from './HowItWorks';
export { default as WhatYouGet } from './WhatYouGet';
export { default as WhoThisIsFor } from './WhoThisIsFor';
export { default as Testimonials } from './Testimonials';
export { default as TrustSignals } from './TrustSignals';
export { default as Pricing } from './Pricing';
export { default as FAQ } from './FAQ';
export { default as CTA } from './CTA';